version: 0.0
os: linux
files:
  - source: /
    destination: /usr/cddemo
    overwrite: true
permissions:
  - object: /usr/cddemo/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
permissions:
  - object: /usr/cddemo/codedeploy
    owner: root
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/af ter_install.sh
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 180
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 180

